### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by imgen** [benbishop/MonkeyArms#2]
I get error when try to compile
D:\Learn\MonkeyArms\MonkeyArms\MonkeyArmsPCL\DI.cs(7,7): Error CS0246: The type or namespace name 'TinyIoC' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (MonkeyArmsPCL)

Also two warnings:

C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(5,5): Warning MSB3268: The primary reference "TinyIOC" could not be resolved because it has an indirect dependency on the framework assembly "System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" which could not be resolved in the currently targeted framework. ".NETPortable,Version=v4.0,Profile=Profile136". To resolve this problem, either remove the reference "TinyIOC" or retarget your application to a framework version which contains "System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089". (MSB3268) (MonkeyArmsPCL)

C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(5,5): Warning MSB3268: The primary reference "TinyIOC" could not be resolved because it has an indirect dependency on the framework assembly "mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" which could not be resolved in the currently targeted framework. ".NETPortable,Version=v4.0,Profile=Profile136". To resolve this problem, either remove the reference "TinyIOC" or retarget your application to a framework version which contains "mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089". (MSB3268) (MonkeyArmsPCL)

This is not a good sign. Could you help fix it?

**Comment by benbishop** [comment]
Hi Imgen,
I started this project before PCLs were officially supported by Xamarin, so there's definitely some kinks to work out in regards to DLLs. To try and address your issue, I switched the TinyIOC dll to a PCL version that I compiled from this branch of TinyIOC:
https://github.com/mgernand/TinyIoC

Let me know if this helps. If not, are you using Xamarin Studio or VisualStudio?

**Comment by imgen** [comment]
Now use the portable version of IoC, I can compile fine.
But why not use it in the project?
I am using VS2012 and the latest version of Xamarin Studio, is that the reason why it does not compile?
What version of Xamarin Studio/Visual Studio are you using?

**Comment by benbishop** [comment]
Hi Imgen,
I pushed the new TinyIOC PCL to the repo this morning. Are you not able to use that one?

I'm using the latest version of XS on OSX. I was asking about VS/XS in case you were still having issues. If you were still experiencing issues, I was going to set up the same environment as you to better troubleshoot.

**Comment by imgen** [comment]
After using the PCL version, everything compiles fine. Thanks.

**Comment by sawilde** [comment]
I found that installing [Microsoft .NET Portable Library Reference Assemblies 4.6](http://www.microsoft.com/en-us/download/confirmation.aspx?id=40727) helped when I had a similar issue
